version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - pagerank_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/pagerank.db
      - PYTHONPATH=/app
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev

  db:
    image: alpine:latest
    volumes:
      - pagerank_data:/data
    command: /bin/sh -c "mkdir -p /data && tail -f /dev/null"

volumes:
  pagerank_data: