"""add rules_config to simulations

Revision ID: add_rules_config_002
Revises: add_page_types_001
Create Date: 2025-08-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_rules_config_002'
down_revision: Union[str, None] = 'add_page_types_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('rules_config', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'rules_config')
    # ### end Alembic commands ###